version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: messaging_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messaging_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - messaging_network

  redis:
    image: redis:latest
    container_name: messaging_redis
    ports:
      - "6379:6379"
    networks:
      - messaging_network

volumes:
  postgres_data:

networks:
  messaging_network:
    driver: bridge
